# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setStyleSheet("background-image: url(:/background/game_background.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lightbulb1 = QtWidgets.QPushButton(self.centralwidget)
        self.lightbulb1.setGeometry(QtCore.QRect(40, 370, 111, 181))
        self.lightbulb1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.lightbulb1.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-image: url(:/lightbulbs/lightbulb_off.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.lightbulb1.setText("")
        self.lightbulb1.setObjectName("lightbulb1")
        self.lightbulb2 = QtWidgets.QPushButton(self.centralwidget)
        self.lightbulb2.setGeometry(QtCore.QRect(190, 370, 111, 181))
        self.lightbulb2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.lightbulb2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-image: url(:/lightbulbs/lightbulb_off.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.lightbulb2.setText("")
        self.lightbulb2.setObjectName("lightbulb2")
        self.lightbulb3 = QtWidgets.QPushButton(self.centralwidget)
        self.lightbulb3.setGeometry(QtCore.QRect(350, 370, 111, 181))
        self.lightbulb3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.lightbulb3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-image: url(:/lightbulbs/lightbulb_off.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.lightbulb3.setText("")
        self.lightbulb3.setObjectName("lightbulb3")
        self.lightbulb4 = QtWidgets.QPushButton(self.centralwidget)
        self.lightbulb4.setGeometry(QtCore.QRect(500, 370, 111, 181))
        self.lightbulb4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.lightbulb4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-image: url(:/lightbulbs/lightbulb_off.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.lightbulb4.setText("")
        self.lightbulb4.setObjectName("lightbulb4")
        self.lightbulb5 = QtWidgets.QPushButton(self.centralwidget)
        self.lightbulb5.setGeometry(QtCore.QRect(650, 370, 111, 181))
        self.lightbulb5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.lightbulb5.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-image: url(:/lightbulbs/lightbulb_off.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.lightbulb5.setText("")
        self.lightbulb5.setObjectName("lightbulb5")
        self.computer = QtWidgets.QLabel(self.centralwidget)
        self.computer.setGeometry(QtCore.QRect(270, 60, 251, 221))
        self.computer.setStyleSheet("border-image: url(:/computer/computer.png);")
        self.computer.setText("")
        self.computer.setObjectName("computer")
        self.number = QtWidgets.QLabel(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(300, 90, 191, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.number.setFont(font)
        self.number.setStyleSheet("qproperty-alignment: \'AlignCenter\';")
        self.number.setObjectName("number")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.number.setText(_translate("MainWindow", "20"))
import main_window_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
